# Generated by Django 3.1.2 on 2020-10-27 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskWork',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=10)),
                ('post_type', models.CharField(choices=[('1', 'FREE'), ('2', 'PAID')], max_length=10)),
                ('priority', models.CharField(choices=[('1', 'high'), ('2', 'medium'), ('3', 'low'), ('4', 'normal')], max_length=10)),
                ('remarks', models.TextField()),
                ('task_status', models.CharField(choices=[('1', 'assigned'), ('2', 'completed'), ('3', 'rejected')], max_length=10)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
