# Generated by Django 3.1.2 on 2020-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskwork',
            name='id',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskwork',
            name='post_type',
            field=models.CharField(choices=[('1', 'COD'), ('2', 'PAID')], max_length=10),
        ),
    ]
